<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AHiddenFormForEditingTheUserDb.aspx.cs" Inherits="VirtualCurrencyWebSvc.AHiddenFormForEditingTheUserDb" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" 
            DataKeyNames="Id" DataSourceID="SqlDataSource1" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateSelectButton="True" AutoGenerateColumns="False">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                    ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Pin" HeaderText="Pin" SortExpression="Pin" />
                <asp:BoundField DataField="Password" HeaderText="Password" 
                    SortExpression="Password" />
                <asp:BoundField DataField="Gender" HeaderText="Gender" 
                    SortExpression="Gender" />
                <asp:BoundField DataField="AccountStatus" HeaderText="AccountStatus" 
                    SortExpression="AccountStatus" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="AliasName" HeaderText="AliasName" 
                    SortExpression="AliasName" />
                <asp:BoundField DataField="AliasPicture" HeaderText="AliasPicture" 
                    SortExpression="AliasPicture" />
                <asp:BoundField DataField="ProfilePicture" HeaderText="ProfilePicture" 
                    SortExpression="ProfilePicture" />
                <asp:BoundField DataField="ProfilePictureSmall" 
                    HeaderText="ProfilePictureSmall" SortExpression="ProfilePictureSmall" />
                <asp:CheckBoxField DataField="Anonymous" HeaderText="Anonymous" 
                    SortExpression="Anonymous" />
                <asp:BoundField DataField="AuthKey" HeaderText="AuthKey" 
                    SortExpression="AuthKey" />
                <asp:BoundField DataField="CreatedBy" HeaderText="CreatedBy" 
                    SortExpression="CreatedBy" />
                <asp:BoundField DataField="CreatedDate" HeaderText="CreatedDate" 
                    SortExpression="CreatedDate" />
                <asp:BoundField DataField="LastChangedBy" HeaderText="LastChangedBy" 
                    SortExpression="LastChangedBy" />
                <asp:BoundField DataField="LastChangedDate" HeaderText="LastChangedDate" 
                    SortExpression="LastChangedDate" />
                <asp:CheckBoxField DataField="Deleted" HeaderText="Deleted" 
                    SortExpression="Deleted" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            SelectCommand="SELECT * FROM [RegisteredUser]" 
            ConnectionString="<%$ ConnectionStrings:UserManagement.Properties.Settings.RegisteredUsersConnectionString %>" 
            DeleteCommand="DELETE FROM [RegisteredUser] WHERE [Id] = @original_Id" 
            InsertCommand="INSERT INTO [RegisteredUser] ([Name], [Pin], [Password], [Gender], [AccountStatus], [Email], [AliasName], [AliasPicture], [ProfilePicture], [ProfilePictureSmall], [Anonymous], [AuthKey], [CreatedBy], [CreatedDate], [LastChangedBy], [LastChangedDate], [Deleted]) VALUES (@Name, @Pin, @Password, @Gender, @AccountStatus, @Email, @AliasName, @AliasPicture, @ProfilePicture, @ProfilePictureSmall, @Anonymous, @AuthKey, @CreatedBy, @CreatedDate, @LastChangedBy, @LastChangedDate, @Deleted)" 
            OldValuesParameterFormatString="original_{0}" 
            
            UpdateCommand="UPDATE [RegisteredUser] SET [Name] = @Name, [Pin] = @Pin, [Password] = @Password, [Gender] = @Gender, [AccountStatus] = @AccountStatus, [Email] = @Email, [AliasName] = @AliasName, [AliasPicture] = @AliasPicture, [ProfilePicture] = @ProfilePicture, [ProfilePictureSmall] = @ProfilePictureSmall, [Anonymous] = @Anonymous, [AuthKey] = @AuthKey, [CreatedBy] = @CreatedBy, [CreatedDate] = @CreatedDate, [LastChangedBy] = @LastChangedBy, [LastChangedDate] = @LastChangedDate, [Deleted] = @Deleted WHERE [Id] = @original_Id">
            <DeleteParameters>
                <asp:Parameter Name="original_Id" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Pin" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Gender" Type="Int32" />
                <asp:Parameter Name="AccountStatus" Type="Int32" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="AliasName" Type="String" />
                <asp:Parameter Name="AliasPicture" Type="String" />
                <asp:Parameter Name="ProfilePicture" Type="String" />
                <asp:Parameter Name="ProfilePictureSmall" Type="String" />
                <asp:Parameter Name="Anonymous" Type="Boolean" />
                <asp:Parameter Name="AuthKey" Type="String" />
                <asp:Parameter Name="CreatedBy" Type="Int32" />
                <asp:Parameter Name="CreatedDate" Type="DateTime" />
                <asp:Parameter Name="LastChangedBy" Type="Int32" />
                <asp:Parameter Name="LastChangedDate" Type="DateTime" />
                <asp:Parameter Name="Deleted" Type="Boolean" />
                <asp:Parameter Name="original_Id" Type="Int32" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Pin" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Gender" Type="Int32" />
                <asp:Parameter Name="AccountStatus" Type="Int32" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="AliasName" Type="String" />
                <asp:Parameter Name="AliasPicture" Type="String" />
                <asp:Parameter Name="ProfilePicture" Type="String" />
                <asp:Parameter Name="ProfilePictureSmall" Type="String" />
                <asp:Parameter Name="Anonymous" Type="Boolean" />
                <asp:Parameter Name="AuthKey" Type="String" />
                <asp:Parameter Name="CreatedBy" Type="Int32" />
                <asp:Parameter Name="CreatedDate" Type="DateTime" />
                <asp:Parameter Name="LastChangedBy" Type="Int32" />
                <asp:Parameter Name="LastChangedDate" Type="DateTime" />
                <asp:Parameter Name="Deleted" Type="Boolean" />
            </InsertParameters>
        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
