//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payments.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api username. E.g.: esesel_1263685459_biz_api1.computer.org")]
        public string PayPalApiUsername {
            get {
                return ((string)(this["PayPalApiUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api password. E.g.: FXNAHJBTYDV78EKY")]
        public string PayPalApiPassword {
            get {
                return ((string)(this["PayPalApiPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api signature. E.g.: Av1EF0H5TSuNjzjJE9jxc9HZacPmA40e7pFXXvJvGQatESCiRfVIyQo" +
            "W")]
        public string PayPalApiSignature {
            get {
                return ((string)(this["PayPalApiSignature"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api environment. E.g.: sandbox")]
        public string PayPalApiEnvironment {
            get {
                return ((string)(this["PayPalApiEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api server. E.g.: http://www.sandbox.paypal.com")]
        public string PayPalApiServer {
            get {
                return ((string)(this["PayPalApiServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api return. E.g.: http://localhost/CheckoutReview.aspx?operation=confirm")]
        public string PayPalApiReturn {
            get {
                return ((string)(this["PayPalApiReturn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your api cancel. E.g.: http://localhost/CheckoutCancel.aspx?operation=cancel")]
        public string PayPalApiCancel {
            get {
                return ((string)(this["PayPalApiCancel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("you_must_define_your_own_db")]
        public string PayPalDb {
            get {
                return ((string)(this["PayPalDb"]));
            }
        }
    }
}
